"""appointment_notify_overrides

Revision ID: 520851e01570
Revises: ab6d9264a6cb
Create Date: 2026-05-06 19:08:23.427371

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '520851e01570'
down_revision: str | None = 'ab6d9264a6cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_notify_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_notify_overrides', schema=None) as batch_op:
        batch_op.create_index('idx_appt_notify_appt', ['appointment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment_notify_overrides', schema=None) as batch_op:
        batch_op.drop_index('idx_appt_notify_appt')

    op.drop_table('appointment_notify_overrides')
    # ### end Alembic commands ###
